image: node:8
cache:
  paths:
  - node_modules/
build:
  script:
  - npm install
  - npm run build
  artifacts:
    paths:
    - build
  only:
  - master
test:
  script:
  - npm install
  - npm run test
  artifacts:
    paths:
    - build
  only:
  - master
